### ISSUE TITLE
怎么样安装?

### ISSUE THREAD

**Issue by uiue** [gxvv/react-webuploader#1]
`npm install react-webuploader`

`
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-webuploader"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/react-webuploader
npm ERR! 404 
npm ERR! 404 'react-webuploader' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-starter-kit'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
`

**Comment by gxvv** [comment]
```npm i git+https://github.com/gxvv/react-webuploader.git```

未发布npm包，因为打包了jquery，所以体积很大:neutral_face:

**Comment by uiue** [comment]
嗯. 安装好了.
在.js里引用`import Webuploader from 'WebUploader.jsx';`
`npm start`之后报错:
`ERROR in ./app/js/pages/details.js
Module not found: Error: Cannot resolve module 'WebUploader.jsx' in /Users/tiger/Downloads/webapp/app/js/pages
 @ ./app/js/pages/details.js 13:19-45`

**Comment by uiue** [comment]
`import Webuploader from WebUploader.jsx;`
如果不加''号, 则报错
`Module build failed: SyntaxError: Unexpected token (4:24)`

**Comment by gxvv** [comment]
因为没有入口文件，需要通过路径去引入;

语法上是需要引号的

**Comment by uiue** [comment]
还是不知道怎么导入
`import WebUploader from '/node_modules/react-webuploader/src/Components/WebUploader.jsx';`

这样导入报错

**Comment by gxvv** [comment]
`./node_modules/react-webuploader/src/Components/WebUploader.jsx`
路径前面要加个点吧

**Comment by uiue** [comment]
粗心了，感谢！
