### ISSUE TITLE
uploaderConfig的name(fileVal)属性设置无效

### ISSUE THREAD

**Issue by NAMEs** [gxvv/react-webuploader#2]
<WebUploader uploaderConfig={{server: 'url', pick: '#pick', auto: true,name:'filename'}} styleConfig={{width: 200}}/>

uploaderConfig的name(fileVal)属性设置无效

**Comment by gxvv** [comment]
查看下Webuploader的[源码](https://github.com/gxvv/react-webuploader/blob/a54b6d02161ccac534a59e6d2ccc9a2e9ab9a8d1/src/vendor/webuploader.html5only.js#L3205)

`fileVal`类型是字符串，设置的时候应该直接用`fileVal: 'filename'`吧

**Comment by NAMEs** [comment]
<WebUploader uploaderConfig={{server: 'url', pick: '#pick', auto: true,fileVal:'filename'}} styleConfig={{width: 200}}/>

uploaderConfig的name(fileVal)属性设置无效,依旧

**Comment by gxvv** [comment]
可以在[Webuploader初始化](https://github.com/gxvv/react-webuploader/blob/master/src/Components/WebUploader.jsx#L39)时，查看下配置是否正确传入。

**Comment by NAMEs** [comment]
ths
