### ISSUE TITLE
没发布到 npm 包管理吗？

### ISSUE THREAD

**Issue by qq645381995** [gxvv/react-webuploader#3]
如题

**Comment by gxvv** [comment]
>npm i git+https://github.com/gxvv/react-webuploader.git
>未发布npm包，因为打包了jquery，所以体积很大:neutral_face:

#1 是的，没有发布

**Comment by qq645381995** [comment]
jquery  不也是 npm包吗？ 你依赖不就行了 ？

**Comment by gxvv** [comment]
我意思插件里打包了jQuery，我自己觉得这样做不好。

不发布npm包是因为我觉得这个做的不好，所以不想发布。

如果你想要使用，可以使用上面提供的命令安装。

**Comment by qq645381995** [comment]
恩  那你会迭代吗？

**Comment by gxvv** [comment]
练习用的，现在用不上React了，不更新了。
